"""Add hostel_link to City

Revision ID: 180856a3ec19
Revises: 
Create Date: 2025-02-15 19:30:59.737563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180856a3ec19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms_acceptance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student')
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostel_link', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('hostel_link')

    op.create_table('student',
    sa.Column('roll', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('marks', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('roll')
    )
    op.drop_table('terms_acceptance')
    # ### end Alembic commands ###
